import Route from '@ioc:Adonis/Core/Route'
const accion_path = '../../../app/Presentacion/Mantenimiento/ControladorMantenimiento'

Route.get('api/v1/mantenimiento/exportar-historial', accion_path + '.exportarAXLSX')
Route.group(() => {
  Route.get('listar-placas', accion_path + '.listarPlacas')
  Route.get('listar-placas-todas', accion_path + '.listarPlacasTodas')
  Route.get('listar-actividades', accion_path + '.listarActividades')
  Route.get('plantillas/alistamiento', accion_path + '.descargarPlantillaAlistamiento')
  Route.get('plantillas/preventivo-correctivo', accion_path + '.descargarPlantillaPreventivoCorrectivo')
  Route.get('visualizar-preventivo', accion_path + '.visualizarPreventivo')
  Route.get('visualizar-correctivo', accion_path + '.visualizarCorrectivo')
  Route.get('visualizar-alistamiento', accion_path + '.visualizarAlistamiento')
   Route.get('visualizar-autorizacion', accion_path + '.visualizarAutorizacion')
  Route.get('listar-historial', accion_path + '.listarHistorial')
  Route.get('jobs', accion_path + '.listarTrabajosProgramados')
  Route.get('jobs-fallidos', accion_path + '.listarTrabajosFallidos')
  Route.get('jobs/:jobId', accion_path + '.obtenerTrabajo')
  Route.post('jobs-fallidos/:jobId/reintentar', accion_path + '.reintentarTrabajoFallido')
  Route.post('guardar-mantenimieto', accion_path + '.guardarMantenimiento')
  Route.post('guardar-preventivo', accion_path + '.guardarPreventivo')
  Route.post('guardar-correctivo', accion_path + '.guardarCorrectivo')
  Route.post('guardar-alistamiento', accion_path + '.guardarAlistamiento')
  Route.post('guardar-autorizacion', accion_path + '.guardarAutorizacion')
  Route.post('bulk/preventivo', accion_path + '.cargaMasivaPreventivo')
  Route.post('bulk/preventivo/xlsx', accion_path + '.cargaMasivaPreventivoExcel')
  Route.post('bulk/correctivo', accion_path + '.cargaMasivaCorrectivo')
  Route.post('bulk/correctivo/xlsx', accion_path + '.cargaMasivaCorrectivoExcel')
  Route.post('bulk/alistamiento', accion_path + '.cargaMasivaAlistamiento')
  Route.post('bulk/alistamiento/xlsx', accion_path + '.cargaMasivaAlistamientoExcel')
  Route.post('bulk/autorizacion', accion_path + '.cargaMasivaAutorizacion')
  Route.post('bulk/autorizacion/xlsx', accion_path + '.cargaMasivaAutorizacionExcel')
}).prefix('api/v1/mantenimiento').middleware('autenticacionJwt')

Route.group(() => {
  Route.get('listar-placas', accion_path + '.listarPlacas')
  Route.get('plantillas/alistamiento', accion_path + '.descargarPlantillaAlistamiento')
  Route.get('plantillas/preventivo-correctivo', accion_path + '.descargarPlantillaPreventivoCorrectivo')
  Route.get('visualizar-preventivo', accion_path + '.visualizarPreventivo')
  Route.get('visualizar-correctivo', accion_path + '.visualizarCorrectivo')
  Route.get('visualizar-alistamiento', accion_path + '.visualizarAlistamiento')
   Route.get('visualizar-autorizacion', accion_path + '.visualizarAutorizacion')
  Route.get('listar-historial', accion_path + '.listarHistorial')
  Route.get('jobs', accion_path + '.listarTrabajosProgramados')
  Route.get('jobs-fallidos', accion_path + '.listarTrabajosFallidos')
  Route.get('jobs/:jobId', accion_path + '.obtenerTrabajo')
  Route.post('jobs-fallidos/:jobId/reintentar', accion_path + '.reintentarTrabajoFallido')
  Route.post('guardar-mantenimieto', accion_path + '.guardarMantenimiento')
  Route.post('guardar-preventivo', accion_path + '.guardarPreventivo')
  Route.post('guardar-correctivo', accion_path + '.guardarCorrectivo')
  Route.post('guardar-alistamiento', accion_path + '.guardarAlistamiento')
  Route.post('guardar-autorizacion', accion_path + '.guardarAutorizacion')
  Route.post('bulk/preventivo', accion_path + '.cargaMasivaPreventivo')
  Route.post('bulk/preventivo/xlsx', accion_path + '.cargaMasivaPreventivoExcel')
  Route.post('bulk/correctivo', accion_path + '.cargaMasivaCorrectivo')
  Route.post('bulk/correctivo/xlsx', accion_path + '.cargaMasivaCorrectivoExcel')
  Route.post('bulk/alistamiento', accion_path + '.cargaMasivaAlistamiento')
  Route.post('bulk/alistamiento/xlsx', accion_path + '.cargaMasivaAlistamientoExcel')
  Route.post('bulk/autorizacion', accion_path + '.cargaMasivaAutorizacion')
  Route.post('bulk/autorizacion/xlsx', accion_path + '.cargaMasivaAutorizacionExcel')

}).prefix('api/v2/mantenimiento').middleware('autenticacionVigia')

Route.group(() => {
  Route.get('listar-actividades', accion_path + '.listarActividades')

}).prefix('api/v2/mantenimiento').middleware('autenticacionVigia')
